
package POO.Enums;

======================
CONCEPT INTRODUCTION
======================

Enums (Enumerations) are special Java types used to define collections of constants.
They represent a fixed set of related values that do not change, making code more
readable, type-safe, and less error-prone than using plain integers or strings.

Enums are particularly useful when you have a variable that should only hold one
of a predefined set of values, such as days of the week, card suits, status codes,
or directions.

Benefits of using enums:
- Type safety: compiler prevents invalid values
- Readability: meaningful names instead of magic numbers
- Maintainability: all related constants in one place
- Built-in methods: enums come with useful methods like values() and valueOf()

Syntax:
enum EnumName {
    CONSTANT1, CONSTANT2, CONSTANT3
}

public class EnumIntro {
    
    enum Day {
        MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY, SUNDAY
    }

    enum Priority {
        LOW, MEDIUM, HIGH, CRITICAL
    }

    enum Status {
        PENDING, APPROVED, REJECTED, IN_PROGRESS
    }

    public static void main(String[] args) {
        
        System.out.println("=== Basic enum usage ===");
        Day today = Day.MONDAY;
        System.out.println("Today is: " + today);

        System.out.println("\n=== Comparing enums ===");
        if (today == Day.MONDAY) {
            System.out.println("Start of the work week!");
        }

        System.out.println("\n=== Using enums in switch ===");
        Priority taskPriority = Priority.HIGH;
        switch (taskPriority) {
            case LOW:
                System.out.println("Handle when convenient");
                break;
            case MEDIUM:
                System.out.println("Schedule for this week");
                break;
            case HIGH:
                System.out.println("Handle today");
                break;
            case CRITICAL:
                System.out.println("Drop everything and handle now!");
                break;
        }

        System.out.println("\n=== Iterating through all enum values ===");
        System.out.println("All days of the week:");
        for (Day day : Day.values()) {
            System.out.println("  - " + day);
        }

        System.out.println("\n=== Converting String to enum ===");
        String statusText = "APPROVED";
        Status orderStatus = Status.valueOf(statusText);
        System.out.println("Order status: " + orderStatus);

        System.out.println("\n=== Enum methods ===");
        System.out.println("Today's ordinal position: " + today.ordinal());
        System.out.println("Today's name: " + today.name());
    }
}

======================
EXPLANATION
======================

EXPLANATION:
- Enums are a special class type that represents a group of constants (unchangeable variables)
- Each enum constant is an instance of the enum type, created automatically by Java
- Enum constants are implicitly public, static, and final
- Enums cannot be instantiated using the new keyword
- By convention, enum constants are written in UPPERCASE with underscores for multi-word names
- Enums can be compared using == operator because each constant is a singleton instance
- Switch statements work exceptionally well with enums, providing compile-time checking
- All enums implicitly extend java.lang.Enum and cannot extend other classes

The values() method returns an array containing all enum constants in declaration order.
This is automatically generated by the compiler and is useful for iteration. Each enum
constant has a position called ordinal, starting from 0, which represents its order in
the declaration.

The valueOf(String) method converts a string to the corresponding enum constant. The
string must exactly match the enum constant name, or an IllegalArgumentException is thrown.
This is useful when reading enum values from configuration files or user input.

When you use enums in switch statements, the compiler ensures all possible cases are
handled if you want exhaustive checking. This prevents bugs from forgetting to handle
certain enum values, unlike when using integers or strings.

Expected Output:
=== Basic enum usage ===
Today is: MONDAY

=== Comparing enums ===
Start of the work week!

=== Using enums in switch ===
Handle today

=== Iterating through all enum values ===
All days of the week:
  - MONDAY
  - TUESDAY
  - WEDNESDAY
  - THURSDAY
  - FRIDAY
  - SATURDAY
  - SUNDAY

=== Converting String to enum ===
Order status: APPROVED

=== Enum methods ===
Today's ordinal position: 0
Today's name: MONDAY

QUICK REFERENCE:
enum Name { VALUE1, VALUE2 }  → enum declaration
EnumName.VALUE                → accessing enum constant
EnumName.values()             → get array of all constants
EnumName.valueOf(String)      → convert string to enum
enumValue.ordinal()           → get position index (starts at 0)
enumValue.name()              → get constant name as string

COMMON MISTAKES:
- Trying to create enum instances with new keyword (enums cannot be instantiated)
- Using lowercase for enum constants (convention is UPPERCASE)
- Comparing enums with equals() instead of == (both work, but == is preferred and safer)
- Forgetting that valueOf() throws exception for invalid strings (always validate input)
- Using ordinal() for business logic (ordinals can change if you reorder constants)
- Trying to extend an enum or make enum extend another class (not allowed in Java)

LEARN MORE:
https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html
(Section: Enum Types)
```